---
permalink: intro-family.html 
keywords: introduction, what E-Series is, e-series, SANtricity, CLI, system manager, unified manager 
summary: NetApp E-Series 제품군은 단순하고 관리가 쉬우며 엔터프라이즈급 안정성을 갖춘 빠른 블록 스토리지가 필요한 고대역폭 애플리케이션을 위한 스토리지 및 애플리케이션 데이터 관리 서비스를 제공합니다. 
---
= E-Series 스토리지 시스템 제품군 소개
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


NetApp E-Series 스토리지 제품군은 유연하고 비용 효율적인 클라우드 백업 및 복구 기능을 제공하며, 엔터프라이즈급 안정성과 더불어 단순하고 관리가 쉬우며 빠른 블록 스토리지가 필요한 전용 고대역폭 애플리케이션에 맞게 설계되었습니다.



== E-Series 플랫폼

E-Series 스토리지 시스템은 2U 또는 4U 폼 팩터에서 여러 드라이브 유형을 처리할 수 있는 애플리케이션 인식 데이터 관리 툴을 사용합니다. 스토리지 시스템을 여러 인터페이스 유형 및 다양한 호스트 운영 체제에서 SAN에 연결할 수 있습니다.

E-Series 스토리지 시스템에는 다음과 같은 플랫폼 모델이 포함됩니다.



=== EF600 및 EF300

빅데이터 분석 및 데이터베이스와 같은 최고 수준의 성능이 필요한 워크로드를 위해 특별히 설계되었습니다.

https://www.netapp.com/pdf.html?item=/media/19339-DS-4082.pdf["EF-Series 데이터시트를 읽어 보십시오"^].



=== E5700

엔터프라이즈급 안정성을 갖춘 고성능 및 데이터 집약적 대역폭 애플리케이션을 위해 제작되었습니다.

https://www.netapp.com/pdf.html?item=/media/7572-ds-3894.pdf["E5700 데이터시트를 읽어 보십시오"^].



=== E2800

전용 앱을 위한 혼합 워크로드 성능과 안정성이 필요한 소규모 기업 및 원격 사무실에 적합합니다.

https://www.netapp.com/pdf.html?item=/media/7573-ds-3805.pdf["E2800 데이터시트를 읽어 보십시오"^].



== SANtricity 소프트웨어

SANtricity 소프트웨어는 네트워크에서 스토리지 시스템을 확인, 프로비저닝 및 관리하는 데 사용되는 System Manager 및 Unified Manager 웹 기반 인터페이스를 모두 제공합니다.

https://www.netapp.com/pdf.html?item=/media/7676-ds-3891.pdf["SANtricity 소프트웨어 데이터시트를 읽어 보십시오"^].



=== SANtricity 시스템 관리자

System Manager는 각 컨트롤러에 내장된 웹 기반 관리 소프트웨어입니다. 사용자 인터페이스에 액세스하려면 브라우저에서 컨트롤러의 IP 주소를 가리킵니다. 설치 마법사를 사용하면 시스템 구성을 시작할 수 있습니다.

* 직관적인 워크플로 마법사 및 상황별 도움말로 구성 작업이 간소해집니다.
* 소프트웨어를 통해 고밀도 엔클로저의 손실 보호, SSD의 마모 수명 및 성능 스마트 관리와 같은 하드웨어 기능을 활용할 수 있는 구성 후보를 제안합니다.
* 정교한 성능 모니터링을 통해 시스템 레벨에서 개별 드라이브까지 정보를 보거나 성능 데이터를 내보내어 추가 분석할 수 있습니다.
* SSD 캐시 또는 데이터 캐시 관리와 같은 튜닝 작업은 모두 온라인 상태에서 수행됩니다. 복구가 필요할 때 SANtricity Recovery Guru에서 단계별 지침을 제공합니다.


로 이동합니다 https://docs.netapp.com/us-en/e-series-santricity/system-manager/index.html["SANtricity 시스템 관리자 문서 사이트입니다"]에서 스토리지 어레이의 계획, 구성, 관리 및 문제 해결 방법에 대한 정보를 찾을 수 있습니다.



=== SANtricity 유니파이드 관리자

Unified Manager는 전체 도메인을 관리하는 데 사용되는 웹 기반 소프트웨어입니다. 중앙 뷰에서 E2800, EF280, EF300, E5700, EF570, 기타 최신 E-Series 및 EF-Series 어레이의 상태를 확인할 수 있습니다. EF600을 지원합니다. 선택한 스토리지 배열에 대해 배치 작업을 수행할 수도 있습니다.

* 단일 창에서 상태를 보고, 어레이를 그룹으로 구성하고, 여러 어레이에 대한 SANtricity OS를 업데이트하고, 각 어레이에 대한 온박스 SANtricity 시스템 관리자를 시작할 수 있습니다.
* 한 번의 작업으로 여러 스토리지에 대한 경고 및 기타 설정을 빠르게 구성할 수 있습니다.
* SANtricity Unified Manager는 Linux 또는 Windows 관리 서버에 설치되고 브라우저에서 실행됩니다.


로 이동합니다 https://docs.netapp.com/us-en/e-series-santricity/unified-manager/index.html["SANtricity Unified Manager 문서 사이트입니다"]에서는 여러 네트워크 스토리지 어레이에서 스토리지 관리 명령을 실행하는 방법을 배울 수 있습니다.



=== SANtricity 웹 서비스 프록시

웹 서비스 프록시는 오케스트레이션과 자동화를 위한 전체 기능을 갖춘 RESTful API 서버로, 수백 개의 새로운 기존 E-Series 어레이를 관리할 수 있습니다. 프록시는 Windows 또는 Linux 서버에 별도로 설치됩니다. 웹 서비스에는 REST API와 직접 상호 작용할 수 있는 API 문서가 포함되어 있습니다.

에 액세스합니다 https://docs.netapp.com/us-en/e-series/web-services-proxy/index.html["웹 서비스 프록시 문서입니다"].



== CLI를 참조하십시오

CLI(Command Line Interface)는 스토리지 어레이를 구성하고 모니터링하는 방법을 제공하는 소프트웨어 애플리케이션입니다.

CLI를 사용하면 DOS C: 프롬프트, Linux 운영 체제 경로 또는 Solaris 운영 체제 경로와 같은 운영 체제 프롬프트에서 명령을 실행할 수 있습니다.

로 이동합니다 https://docs.netapp.com/us-en/e-series-cli/index.html["SANtricity CLI 문서 사이트입니다"]에서는 CLI 명령을 사용하여 스토리지 어레이를 구성하고 모니터링하는 방법을 배울 수 있습니다.



== 를 참조하십시오

* https://docs.netapp.com/us-en/e-series/index.html["E-Series 시스템 문서"^]
* https://docs.netapp.com/us-en/e-series-santricity/index.html["SANtricity 소프트웨어 문서"^]
* https://docs.netapp.com/us-en/e-series-cli/index.html["SANtricity CLI 문서"^]

