---
settings:
  name: E-Series Family
  search: e-series,e-series-santricity,e-series-cli
  internal:
    pdf_enabled: false
  prod:
    pdf_enabled: false
    harmony_enabled: false
  langs: ko-kr,us-en,de-de,es-es,fr-fr,it-it,pt-br,ja-jp,zh-cn,zh-tw
sidebar:
  entries:
  - title: E-Series 제품군 설명서
    url: "/index.html"
  - title: 법적 고지
    url: "/legal-notices.html"
