---
settings:
  name: E-Series Family
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: ko-kr,us-en,ja-jp,zh-cn,zh-tw
sidebar:
  entries:
  - title: E-Series 제품군 설명서
    url: "/index.html"
product-family:
  search: clouddocs-e-series_main-prod,clouddocs-e-series-santricity_main-prod,clouddocs-e-series-cli_main-prod
  sidebarlinks:
  - title: 모든 문서
    tags: tag_storage_management,tag_data_storage,tag_cli,tag_get_started,tag_SANtricity
    class: active
  - title: 시작하십시오
    tags: tag_get_started
  - title: 데이터 스토리지
    tags: tag_data_storage
  - title: 스토리지 관리
    tags: tag_storage_management, tag_SANtricity
  tiles:
  - title: E-Series 제품군에 대해 알아보십시오
    icon: "./media/groups_line-1.png"
    url: intro-family.html
    summary: E-Series 스토리지 시스템 제품군에 대해 알아보십시오.
    tags: all, tag_get_started
  - title: E-Series 시스템
    icon: "./media/system_line.png"
    url: https://docs.netapp.com/us-en/e-series/index.html
    summary: E-Series 스토리지 시스템을 사용하면 빠른 블록 스토리지 및 엔터프라이즈급 안정성으로 애플리케이션 워크로드를 지원할 수
      있습니다.
    tags: all, tag_data_storage
  - title: SANtricity 소프트웨어
    icon: "./media/config_line.png"
    url: https://docs.netapp.com/us-en/e-series-santricity/index.html
    summary: SANtricity 소프트웨어를 사용하면 웹 기반 인터페이스에서 E-Series 스토리지 시스템을 프로비저닝 및 관리할 수
      있습니다.
    tags: all, tag_storage_management, tag_SANtricity
  - title: 명령줄 인터페이스
    icon: "./media/cli_line.png"
    url: https://docs.netapp.com/us-en/e-series-cli/index.html
    summary: CLI를 사용하여 운영 체제 프롬프트에서 E-Series 스토리지 시스템을 구성 및 모니터링합니다.
    tags: all, tag_storage_management, tag_SANtricity
  - title: 웹 서비스 API
    icon: "./media/api.png"
    url: https://docs.netapp.com/us-en/e-series/web-services-proxy/index.html
    summary: RESTful API를 사용하여 신규 및 기존 E-Series 스토리지 시스템에 워크플로우를 구축하고 자동화할 수 있습니다.
    tags: all, tag_storage_management, tag_SANtricity
